syntax = "proto3";

package commscope;

option go_package = "commscope/pkg/pb";

// message payload request and response

message SendMessageRequest {
    string client_id = 1;
    string text = 2;
}

message SendMessageResponse {
    string status = 1;
    string message_id = 2;
    string created_at = 3;

}
 message GetStatsRequest {}

 message ProtocolStatsResponse {
    string protocol = 1;
    int32 active_connections = 2;
    int64 message_count = 3;
    double p50_latency_ms = 4;
    double p99_latency_ms = 5;
    double throughput = 6;
    
 }

 // Commscope gRPC Service
 service CommScopeService {

    // Unary gRPC
    rpc SendMessage (SendMessageRequest) returns (SendMessageResponse);
    rpc GetStats(GetStatsRequest) returns (ProtocolStatsResponse);


    // Server Streaming
    rpc StreamMessages (GetStatsRequest) returns (stream SendMessageResponse);

    // Client Streaming
    rpc SendBatchMessages (stream SendMessageRequest) returns (SendMessageResponse);

    // Bidirectional Streaming 
    rpc ChatStream (stream SendMessageRequest) returns (stream SendMessageResponse);

 }