// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.1
// source: proto/commscope.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CommScopeService_SendMessage_FullMethodName       = "/commscope.CommScopeService/SendMessage"
	CommScopeService_GetStats_FullMethodName          = "/commscope.CommScopeService/GetStats"
	CommScopeService_StreamMessages_FullMethodName    = "/commscope.CommScopeService/StreamMessages"
	CommScopeService_SendBatchMessages_FullMethodName = "/commscope.CommScopeService/SendBatchMessages"
	CommScopeService_ChatStream_FullMethodName        = "/commscope.CommScopeService/ChatStream"
)

// CommScopeServiceClient is the client API for CommScopeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Commscope gRPC Service
type CommScopeServiceClient interface {
	// Unary gRPC
	SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*SendMessageResponse, error)
	GetStats(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (*ProtocolStatsResponse, error)
	// Server Streaming
	StreamMessages(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SendMessageResponse], error)
	// Client Streaming
	SendBatchMessages(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[SendMessageRequest, SendMessageResponse], error)
	// Bidirectional Streaming
	ChatStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SendMessageRequest, SendMessageResponse], error)
}

type commScopeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCommScopeServiceClient(cc grpc.ClientConnInterface) CommScopeServiceClient {
	return &commScopeServiceClient{cc}
}

func (c *commScopeServiceClient) SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*SendMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendMessageResponse)
	err := c.cc.Invoke(ctx, CommScopeService_SendMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commScopeServiceClient) GetStats(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (*ProtocolStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProtocolStatsResponse)
	err := c.cc.Invoke(ctx, CommScopeService_GetStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commScopeServiceClient) StreamMessages(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SendMessageResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CommScopeService_ServiceDesc.Streams[0], CommScopeService_StreamMessages_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetStatsRequest, SendMessageResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CommScopeService_StreamMessagesClient = grpc.ServerStreamingClient[SendMessageResponse]

func (c *commScopeServiceClient) SendBatchMessages(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[SendMessageRequest, SendMessageResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CommScopeService_ServiceDesc.Streams[1], CommScopeService_SendBatchMessages_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SendMessageRequest, SendMessageResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CommScopeService_SendBatchMessagesClient = grpc.ClientStreamingClient[SendMessageRequest, SendMessageResponse]

func (c *commScopeServiceClient) ChatStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SendMessageRequest, SendMessageResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CommScopeService_ServiceDesc.Streams[2], CommScopeService_ChatStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SendMessageRequest, SendMessageResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CommScopeService_ChatStreamClient = grpc.BidiStreamingClient[SendMessageRequest, SendMessageResponse]

// CommScopeServiceServer is the server API for CommScopeService service.
// All implementations must embed UnimplementedCommScopeServiceServer
// for forward compatibility.
//
// Commscope gRPC Service
type CommScopeServiceServer interface {
	// Unary gRPC
	SendMessage(context.Context, *SendMessageRequest) (*SendMessageResponse, error)
	GetStats(context.Context, *GetStatsRequest) (*ProtocolStatsResponse, error)
	// Server Streaming
	StreamMessages(*GetStatsRequest, grpc.ServerStreamingServer[SendMessageResponse]) error
	// Client Streaming
	SendBatchMessages(grpc.ClientStreamingServer[SendMessageRequest, SendMessageResponse]) error
	// Bidirectional Streaming
	ChatStream(grpc.BidiStreamingServer[SendMessageRequest, SendMessageResponse]) error
	mustEmbedUnimplementedCommScopeServiceServer()
}

// UnimplementedCommScopeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCommScopeServiceServer struct{}

func (UnimplementedCommScopeServiceServer) SendMessage(context.Context, *SendMessageRequest) (*SendMessageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendMessage not implemented")
}
func (UnimplementedCommScopeServiceServer) GetStats(context.Context, *GetStatsRequest) (*ProtocolStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStats not implemented")
}
func (UnimplementedCommScopeServiceServer) StreamMessages(*GetStatsRequest, grpc.ServerStreamingServer[SendMessageResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamMessages not implemented")
}
func (UnimplementedCommScopeServiceServer) SendBatchMessages(grpc.ClientStreamingServer[SendMessageRequest, SendMessageResponse]) error {
	return status.Error(codes.Unimplemented, "method SendBatchMessages not implemented")
}
func (UnimplementedCommScopeServiceServer) ChatStream(grpc.BidiStreamingServer[SendMessageRequest, SendMessageResponse]) error {
	return status.Error(codes.Unimplemented, "method ChatStream not implemented")
}
func (UnimplementedCommScopeServiceServer) mustEmbedUnimplementedCommScopeServiceServer() {}
func (UnimplementedCommScopeServiceServer) testEmbeddedByValue()                          {}

// UnsafeCommScopeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CommScopeServiceServer will
// result in compilation errors.
type UnsafeCommScopeServiceServer interface {
	mustEmbedUnimplementedCommScopeServiceServer()
}

func RegisterCommScopeServiceServer(s grpc.ServiceRegistrar, srv CommScopeServiceServer) {
	// If the following call panics, it indicates UnimplementedCommScopeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CommScopeService_ServiceDesc, srv)
}

func _CommScopeService_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommScopeServiceServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommScopeService_SendMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommScopeServiceServer).SendMessage(ctx, req.(*SendMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommScopeService_GetStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommScopeServiceServer).GetStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommScopeService_GetStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommScopeServiceServer).GetStats(ctx, req.(*GetStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommScopeService_StreamMessages_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetStatsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CommScopeServiceServer).StreamMessages(m, &grpc.GenericServerStream[GetStatsRequest, SendMessageResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CommScopeService_StreamMessagesServer = grpc.ServerStreamingServer[SendMessageResponse]

func _CommScopeService_SendBatchMessages_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CommScopeServiceServer).SendBatchMessages(&grpc.GenericServerStream[SendMessageRequest, SendMessageResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CommScopeService_SendBatchMessagesServer = grpc.ClientStreamingServer[SendMessageRequest, SendMessageResponse]

func _CommScopeService_ChatStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CommScopeServiceServer).ChatStream(&grpc.GenericServerStream[SendMessageRequest, SendMessageResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CommScopeService_ChatStreamServer = grpc.BidiStreamingServer[SendMessageRequest, SendMessageResponse]

// CommScopeService_ServiceDesc is the grpc.ServiceDesc for CommScopeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CommScopeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "commscope.CommScopeService",
	HandlerType: (*CommScopeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendMessage",
			Handler:    _CommScopeService_SendMessage_Handler,
		},
		{
			MethodName: "GetStats",
			Handler:    _CommScopeService_GetStats_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamMessages",
			Handler:       _CommScopeService_StreamMessages_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SendBatchMessages",
			Handler:       _CommScopeService_SendBatchMessages_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "ChatStream",
			Handler:       _CommScopeService_ChatStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/commscope.proto",
}
