// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: proto/commscope.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_proto_commscope_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_commscope_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_proto_commscope_proto_rawDescGZIP(), []int{0}
}

func (x *SendMessageRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *SendMessageRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type SendMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	MessageId     string                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageResponse) Reset() {
	*x = SendMessageResponse{}
	mi := &file_proto_commscope_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageResponse) ProtoMessage() {}

func (x *SendMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_commscope_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageResponse.ProtoReflect.Descriptor instead.
func (*SendMessageResponse) Descriptor() ([]byte, []int) {
	return file_proto_commscope_proto_rawDescGZIP(), []int{1}
}

func (x *SendMessageResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SendMessageResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *SendMessageResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type GetStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsRequest) Reset() {
	*x = GetStatsRequest{}
	mi := &file_proto_commscope_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsRequest) ProtoMessage() {}

func (x *GetStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_commscope_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsRequest.ProtoReflect.Descriptor instead.
func (*GetStatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_commscope_proto_rawDescGZIP(), []int{2}
}

type ProtocolStatsResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Protocol          string                 `protobuf:"bytes,1,opt,name=protocol,proto3" json:"protocol,omitempty"`
	ActiveConnections int32                  `protobuf:"varint,2,opt,name=active_connections,json=activeConnections,proto3" json:"active_connections,omitempty"`
	MessageCount      int64                  `protobuf:"varint,3,opt,name=message_count,json=messageCount,proto3" json:"message_count,omitempty"`
	P50LatencyMs      float64                `protobuf:"fixed64,4,opt,name=p50_latency_ms,json=p50LatencyMs,proto3" json:"p50_latency_ms,omitempty"`
	P99LatencyMs      float64                `protobuf:"fixed64,5,opt,name=p99_latency_ms,json=p99LatencyMs,proto3" json:"p99_latency_ms,omitempty"`
	Throughput        float64                `protobuf:"fixed64,6,opt,name=throughput,proto3" json:"throughput,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ProtocolStatsResponse) Reset() {
	*x = ProtocolStatsResponse{}
	mi := &file_proto_commscope_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtocolStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtocolStatsResponse) ProtoMessage() {}

func (x *ProtocolStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_commscope_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtocolStatsResponse.ProtoReflect.Descriptor instead.
func (*ProtocolStatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_commscope_proto_rawDescGZIP(), []int{3}
}

func (x *ProtocolStatsResponse) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *ProtocolStatsResponse) GetActiveConnections() int32 {
	if x != nil {
		return x.ActiveConnections
	}
	return 0
}

func (x *ProtocolStatsResponse) GetMessageCount() int64 {
	if x != nil {
		return x.MessageCount
	}
	return 0
}

func (x *ProtocolStatsResponse) GetP50LatencyMs() float64 {
	if x != nil {
		return x.P50LatencyMs
	}
	return 0
}

func (x *ProtocolStatsResponse) GetP99LatencyMs() float64 {
	if x != nil {
		return x.P99LatencyMs
	}
	return 0
}

func (x *ProtocolStatsResponse) GetThroughput() float64 {
	if x != nil {
		return x.Throughput
	}
	return 0
}

var File_proto_commscope_proto protoreflect.FileDescriptor

const file_proto_commscope_proto_rawDesc = "" +
	"\n" +
	"\x15proto/commscope.proto\x12\tcommscope\"E\n" +
	"\x12SendMessageRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"k\n" +
	"\x13SendMessageResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\tR\tcreatedAt\"\x11\n" +
	"\x0fGetStatsRequest\"\xf3\x01\n" +
	"\x15ProtocolStatsResponse\x12\x1a\n" +
	"\bprotocol\x18\x01 \x01(\tR\bprotocol\x12-\n" +
	"\x12active_connections\x18\x02 \x01(\x05R\x11activeConnections\x12#\n" +
	"\rmessage_count\x18\x03 \x01(\x03R\fmessageCount\x12$\n" +
	"\x0ep50_latency_ms\x18\x04 \x01(\x01R\fp50LatencyMs\x12$\n" +
	"\x0ep99_latency_ms\x18\x05 \x01(\x01R\fp99LatencyMs\x12\x1e\n" +
	"\n" +
	"throughput\x18\x06 \x01(\x01R\n" +
	"throughput2\xa1\x03\n" +
	"\x10CommScopeService\x12L\n" +
	"\vSendMessage\x12\x1d.commscope.SendMessageRequest\x1a\x1e.commscope.SendMessageResponse\x12H\n" +
	"\bGetStats\x12\x1a.commscope.GetStatsRequest\x1a .commscope.ProtocolStatsResponse\x12N\n" +
	"\x0eStreamMessages\x12\x1a.commscope.GetStatsRequest\x1a\x1e.commscope.SendMessageResponse0\x01\x12T\n" +
	"\x11SendBatchMessages\x12\x1d.commscope.SendMessageRequest\x1a\x1e.commscope.SendMessageResponse(\x01\x12O\n" +
	"\n" +
	"ChatStream\x12\x1d.commscope.SendMessageRequest\x1a\x1e.commscope.SendMessageResponse(\x010\x01B\x12Z\x10commscope/pkg/pbb\x06proto3"

var (
	file_proto_commscope_proto_rawDescOnce sync.Once
	file_proto_commscope_proto_rawDescData []byte
)

func file_proto_commscope_proto_rawDescGZIP() []byte {
	file_proto_commscope_proto_rawDescOnce.Do(func() {
		file_proto_commscope_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_commscope_proto_rawDesc), len(file_proto_commscope_proto_rawDesc)))
	})
	return file_proto_commscope_proto_rawDescData
}

var file_proto_commscope_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_commscope_proto_goTypes = []any{
	(*SendMessageRequest)(nil),    // 0: commscope.SendMessageRequest
	(*SendMessageResponse)(nil),   // 1: commscope.SendMessageResponse
	(*GetStatsRequest)(nil),       // 2: commscope.GetStatsRequest
	(*ProtocolStatsResponse)(nil), // 3: commscope.ProtocolStatsResponse
}
var file_proto_commscope_proto_depIdxs = []int32{
	0, // 0: commscope.CommScopeService.SendMessage:input_type -> commscope.SendMessageRequest
	2, // 1: commscope.CommScopeService.GetStats:input_type -> commscope.GetStatsRequest
	2, // 2: commscope.CommScopeService.StreamMessages:input_type -> commscope.GetStatsRequest
	0, // 3: commscope.CommScopeService.SendBatchMessages:input_type -> commscope.SendMessageRequest
	0, // 4: commscope.CommScopeService.ChatStream:input_type -> commscope.SendMessageRequest
	1, // 5: commscope.CommScopeService.SendMessage:output_type -> commscope.SendMessageResponse
	3, // 6: commscope.CommScopeService.GetStats:output_type -> commscope.ProtocolStatsResponse
	1, // 7: commscope.CommScopeService.StreamMessages:output_type -> commscope.SendMessageResponse
	1, // 8: commscope.CommScopeService.SendBatchMessages:output_type -> commscope.SendMessageResponse
	1, // 9: commscope.CommScopeService.ChatStream:output_type -> commscope.SendMessageResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_commscope_proto_init() }
func file_proto_commscope_proto_init() {
	if File_proto_commscope_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_commscope_proto_rawDesc), len(file_proto_commscope_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_commscope_proto_goTypes,
		DependencyIndexes: file_proto_commscope_proto_depIdxs,
		MessageInfos:      file_proto_commscope_proto_msgTypes,
	}.Build()
	File_proto_commscope_proto = out.File
	file_proto_commscope_proto_goTypes = nil
	file_proto_commscope_proto_depIdxs = nil
}
